using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Afterglow.Core.Interop.Igcl;
using Afterglow.Core.Interop.LevelZero;

namespace Afterglow.Core.Tests;

/// <summary>
/// Pins every IGCL struct Afterglow marshals to the size the OFFICIAL header
/// produces. Expected values were generated by compiling igcl_api.h
/// (github.com/intel/drivers.gpu.control-library, header v1-r1) with clang
/// 22.1.8 targeting x86_64-pc-windows-msvc and dumping the record layouts
/// (docs/research/intel-driver-apis.md records the procedure). A drift here
/// means the C# layout no longer matches the driver ABI and every call using
/// the struct would corrupt or truncate data — exactly the failure mode that
/// produced the false "RTX 50 blocks the curve APIs" claim on the NVIDIA side.
/// </summary>
public class IgclStructLayoutTests
{
    [Fact]
    public void Core_structs_match_the_official_header_sizes()
    {
        Assert.Equal(36, Marshal.SizeOf<CtlInitArgs>());
        Assert.Equal(16, Marshal.SizeOf<CtlApplicationId>());
        Assert.Equal(3, Marshal.SizeOf<CtlAdapterBdf>());
        Assert.Equal(24, Marshal.SizeOf<CtlFirmwareVersion>());
        Assert.Equal(320, Marshal.SizeOf<CtlDeviceAdapterProperties>());
    }

    [Fact]
    public void Adapter_properties_field_offsets_match_the_official_header()
    {
        // The pad bytes after Version (u8 at 4) and before driver_version are
        // where a wrong Pack setting would first show.
        Assert.Equal(32, (int)Marshal.OffsetOf<CtlDeviceAdapterProperties>(nameof(CtlDeviceAdapterProperties.DriverVersion)));
        Assert.Equal(64, (int)Marshal.OffsetOf<CtlDeviceAdapterProperties>(nameof(CtlDeviceAdapterProperties.PciVendorId)));
        Assert.Equal(88, (int)Marshal.OffsetOf<CtlDeviceAdapterProperties>(nameof(CtlDeviceAdapterProperties.Name)));
        Assert.Equal(200, (int)Marshal.OffsetOf<CtlDeviceAdapterProperties>(nameof(CtlDeviceAdapterProperties.AdapterBdf)));
        Assert.Equal(204, (int)Marshal.OffsetOf<CtlDeviceAdapterProperties>(nameof(CtlDeviceAdapterProperties.NumXeCores)));
        Assert.Equal(208, (int)Marshal.OffsetOf<CtlDeviceAdapterProperties>(nameof(CtlDeviceAdapterProperties.Reserved)));
    }

    [Fact]
    public void Telemetry_structs_match_the_official_header_sizes()
    {
        Assert.Equal(8, Marshal.SizeOf<CtlDataValue>());
        Assert.Equal(24, Marshal.SizeOf<CtlTelemetryItem>());
        Assert.Equal(56, Marshal.SizeOf<CtlPsuInfo>());
        Assert.Equal(1024, Unsafe.SizeOf<CtlPowerTelemetry>());
        Assert.Equal(24, Marshal.SizeOf<CtlTempProperties>());
        Assert.Equal(32, Marshal.SizeOf<CtlFreqProperties>());
        Assert.Equal(56, Marshal.SizeOf<CtlFreqState>());
        Assert.Equal(24, Marshal.SizeOf<CtlFreqRange>());
        Assert.Equal(32, Marshal.SizeOf<CtlMemProperties>());
        Assert.Equal(24, Marshal.SizeOf<CtlMemState>());
        Assert.Equal(40, Marshal.SizeOf<CtlMemBandwidth>());
        Assert.Equal(12, Marshal.SizeOf<CtlEngineProperties>());
        Assert.Equal(24, Marshal.SizeOf<CtlEngineStats>());
        Assert.Equal(24, Marshal.SizeOf<CtlPciAddress>());
        Assert.Equal(24, Marshal.SizeOf<CtlPciSpeed>());
        Assert.Equal(64, Marshal.SizeOf<CtlPciProperties>());
        Assert.Equal(32, Marshal.SizeOf<CtlPciState>());
    }

    [Fact]
    public void Power_telemetry_array_offsets_match_the_official_header()
    {
        // The two inline arrays and the Version>0 tail are the highest-risk
        // regions of the 1024-byte block.
        Assert.Equal(208, (int)Marshal.OffsetOf<CtlPowerTelemetry>(nameof(CtlPowerTelemetry.VramEnergyCounter)));
        Assert.Equal(384, (int)Marshal.OffsetOf<CtlPowerTelemetry>(nameof(CtlPowerTelemetry.TotalCardEnergyCounter)));
        Assert.Equal(408, (int)Marshal.OffsetOf<CtlPowerTelemetry>(nameof(CtlPowerTelemetry.Psu)));
        Assert.Equal(688, (int)Marshal.OffsetOf<CtlPowerTelemetry>(nameof(CtlPowerTelemetry.FanSpeed)));
        // GpuVrTemp's offset doubles as the historical pre-V1 struct size the
        // wrapper's last-resort fallback sends to runtimes built against the
        // older header (the Version>0 items were appended, not reserved).
        Assert.Equal(808, (int)Marshal.OffsetOf<CtlPowerTelemetry>(nameof(CtlPowerTelemetry.GpuVrTemp)));
        Assert.Equal(1000, (int)Marshal.OffsetOf<CtlPowerTelemetry>(nameof(CtlPowerTelemetry.VramWriteBandwidth)));
    }

    [Fact]
    public void Fan_structs_match_the_official_header_sizes()
    {
        Assert.Equal(24, Marshal.SizeOf<CtlFanProperties>());
        Assert.Equal(16, Marshal.SizeOf<CtlFanSpeed>());
        Assert.Equal(28, Marshal.SizeOf<CtlFanTempSpeed>());
        Assert.Equal(908, Unsafe.SizeOf<CtlFanSpeedTable>());
        Assert.Equal(936, Unsafe.SizeOf<CtlFanConfig>());
    }

    [Fact]
    public void Overclock_and_power_structs_match_the_official_header_sizes()
    {
        Assert.Equal(48, Marshal.SizeOf<CtlOcControlInfo>());
        Assert.Equal(440, Marshal.SizeOf<CtlOcProperties>());
        // Pre-V1 size (offset of the first appended Version>0 knob block),
        // used by the wrapper's old-runtime fallback.
        Assert.Equal(296, (int)Marshal.OffsetOf<CtlOcProperties>(nameof(CtlOcProperties.VramMemSpeedLimit)));
        Assert.Equal(24, Marshal.SizeOf<CtlOcVfPair>());
        Assert.Equal(8, Marshal.SizeOf<CtlVoltageFrequencyPoint>());
        Assert.Equal(12, Marshal.SizeOf<CtlPowerSustainedLimit>());
        Assert.Equal(8, Marshal.SizeOf<CtlPowerBurstLimit>());
        Assert.Equal(8, Marshal.SizeOf<CtlPowerPeakLimit>());
        Assert.Equal(36, Marshal.SizeOf<CtlPowerLimits>());
        Assert.Equal(20, Marshal.SizeOf<CtlPowerDomainProperties>());
        Assert.Equal(24, Marshal.SizeOf<CtlPowerEnergyCounter>());
    }
}

/// <summary>
/// Same contract for the Level Zero Sysman structs, against zes_api.h from
/// github.com/oneapi-src/level-zero compiled with the same toolchain.
/// </summary>
public class ZesStructLayoutTests
{
    [Fact]
    public void Sysman_structs_match_the_official_header_sizes()
    {
        Assert.Equal(16, Marshal.SizeOf<ZesPciAddress>());
        Assert.Equal(16, Marshal.SizeOf<ZesPciSpeed>());
        Assert.Equal(56, Marshal.SizeOf<ZesPciProperties>());
        Assert.Equal(40, Marshal.SizeOf<ZesPowerProperties>());
        Assert.Equal(16, Marshal.SizeOf<ZesPowerEnergyCounter>());
        Assert.Equal(48, Marshal.SizeOf<ZesFreqProperties>());
        Assert.Equal(64, Marshal.SizeOf<ZesFreqState>());
        Assert.Equal(48, Marshal.SizeOf<ZesTempProperties>());
        Assert.Equal(48, Marshal.SizeOf<ZesMemProperties>());
        Assert.Equal(40, Marshal.SizeOf<ZesMemState>());
        Assert.Equal(32, Marshal.SizeOf<ZesMemBandwidth>());
        Assert.Equal(32, Marshal.SizeOf<ZesEngineProperties>());
        Assert.Equal(16, Marshal.SizeOf<ZesEngineStats>());
    }
}

/// <summary>
/// Pure-logic checks on the telemetry item decoder — no driver needed.
/// </summary>
public class CtlTelemetryItemTests
{
    [Fact]
    public void AsDouble_reads_the_union_member_the_type_field_names()
    {
        var item = new CtlTelemetryItem { Type = CtlDataType.Double };
        item.Value.DataDouble = 42.5;
        Assert.Equal(42.5, item.AsDouble());

        item = new CtlTelemetryItem { Type = CtlDataType.Uint64 };
        item.Value.DataU64 = 123456789;
        Assert.Equal(123456789.0, item.AsDouble());

        item = new CtlTelemetryItem { Type = CtlDataType.Int32 };
        item.Value.Data32 = -7;
        Assert.Equal(-7.0, item.AsDouble());

        item = new CtlTelemetryItem { Type = CtlDataType.Float };
        item.Value.DataFloat = 1.5f;
        Assert.Equal(1.5, item.AsDouble());
    }
}
